// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Fizz.SalesOrder.Models;

namespace Fizz.SalesOrder.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20200730041637_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TodoApi.Models.Order", b =>
                {
                    b.Property<string>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatNo")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SignDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdaeDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdateNo")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("No");

                    b.HasIndex("No")
                        .IsUnique();

                    b.ToTable("orders");
                });

            modelBuilder.Entity("TodoApi.Models.OrderDetail", b =>
                {
                    b.Property<int>("ProNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatNo")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaterialNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SortNo")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdaeDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdateNo")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProNo");

                    b.HasIndex("No");

                    b.HasIndex("ProNo")
                        .IsUnique();

                    b.ToTable("orderDetails");
                });

            modelBuilder.Entity("TodoApi.Models.OrderDetail", b =>
                {
                    b.HasOne("TodoApi.Models.Order", "order")
                        .WithMany("orderDetails")
                        .HasForeignKey("No")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
