// <auto-generated />
using System;
using Fizz.SalesOrder.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fizz.SalesOrder.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20200806063508_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Fizz.SalesOrder.Models.Order", b =>
                {
                    b.Property<string>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatSaleDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatSaleNo")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SignDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdaeSaleDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdateSaleNo")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("No");

                    b.HasIndex("No")
                        .IsUnique();

                    b.ToTable("orders");
                });

            modelBuilder.Entity("Fizz.SalesOrder.Models.OrderDetail", b =>
                {
                    b.Property<int>("ProNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatSaleDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreatSaleNo")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaterialNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OrderNo")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SortNo")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdaeSaleDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdateSaleNo")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProNo");

                    b.HasIndex("OrderNo");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("Fizz.SalesOrder.Models.OrderDetail", b =>
                {
                    b.HasOne("Fizz.SalesOrder.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderNo");
                });
#pragma warning restore 612, 618
        }
    }
}
