variables:
   SOLUTION_PATH: ./Fizz.SalesOrder.sln
   PROJECT_PATH: ./Fizz.SalesOrder/Fizz.SalesOrder.csproj
   SOLUTION_PATH_NAME: FIZZ_SALES_ORDER
   IMAGE_PREFIX: trials/s52
   IMAGE_NAME: ord
   REGISTRY_HOST: hub.iubang.com:5000
   DEPLOY_TARGET: gitlab-runner@byzan.cxist.com
   STACK_NAME: byz-trials

stages:
  - test
  - build_src
  - build_img
  - push_image
  - deploy

test:
  stage: test
  tags: 
    - dotnet
  only:
    - fizzDev
  variables:

  script:
    - dotnet test PROJECT_PATH

build_src:
  stage: build_src
  tags:
    - dotnet
  only:
    - fizzDev
    - dev
    - master
  variables:
    PUBLISH_DIR: publish-$CI_PIPELINE_ID
  script:
    - mkdir -p $PWD/$PUBLISH_DIR
    - echo $PWD/$PUBLISH_DIR
    - dotnet publish -v q $SOLUTION_PATH -c Release -o $PWD/$PUBLISH_DIR --version-suffix 1.0
    - cp -r tools/CI/Dockerfile $PUBLISH_DIR
    - tar -cz -f $SOLUTION_PATH_NAME.tar.gz -C $PUBLISH_DIR .
  artifacts:
    name: "$SOLUTION_PATH_NAME"
    paths:
      - $SOLUTION_PATH_NAME.tar.gz

build_image:
  stage: build_img
  tags:
    - docker
  only:
    - fizzDev
    - dev
    - master
  variables:
    IMAGE_TAG: nightly
    DOCKER_BUILD_DIR: docker_build_$CI_PIPELINE_ID
  script:
    - mkdir -p $DOCKER_BUILD_DIR
    - IMAGE_FULL_NAME=$IMAGE_PREFIX/$IMAGE_NAME:$IMAGE_TAG
    - tar -xzf $SOLUTION_PATH_NAME.tar.gz -C $DOCKER_BUILD_DIR
    - docker build --tag $IMAGE_FULL_NAME $DOCKER_BUILD_DIR
  dependencies:
    - build_src

push_image:
  stage: push_image
  tags:
    - docker
  only:
    - fizzDev
    - master
    - dev
  variables:
    IMAGE_TAG: nightly
    LATEST: 'false'
    PUSH_VERSION: $CI_PIPELINE_ID
    IMAGE_FULL_NAME: $IMAGE_PREFIX/$IMAGE_NAME:$IMAGE_TAG
    CURRENT_PUSH_IMAGE_NAME: $REGISTRY_HOST/$IMAGE_PREFIX/$IMAGE_NAME:$IMAGE_TAG
  script:
    - echo "$CURRENT_PUSH_IMAGE_NAME"
    - docker image tag $IMAGE_FULL_NAME $CURRENT_PUSH_IMAGE_NAME
    - docker image push $CURRENT_PUSH_IMAGE_NAME > /dev/null
    - docker image rm $CURRENT_PUSH_IMAGE_NAME
    - CURRENT_PUSH_IMAGE_NAME=$CURRENT_PUSH_IMAGE_NAME-$CI_PIPELINE_ID
    - docker image tag $IMAGE_FULL_NAME $CURRENT_PUSH_IMAGE_NAME
    - docker image push $CURRENT_PUSH_IMAGE_NAME > /dev/null
    - docker image rm $CURRENT_PUSH_IMAGE_NAME

deploy:
  stage: deploy
  tags:
    - dotnet
  only:
    - fizzDev
    - master
    - dev
  variables:
    STACK_DIR: byzan-deploy/fizz/ord
    STACK_FILE: stack.yaml
  script:
    - ssh -q $DEPLOY_TARGET "mkdir -p ~/$STACK_DIR"
    - scp -q tools/CI/$STACK_FILE $DEPLOY_TARGET:~/$STACK_DIR
    - ssh $DEPLOY_TARGET "docker stack deploy --compose-file ~/$STACK_DIR/$STACK_FILE $STACK_NAME"