// <auto-generated />
using System;
using Fizz.SalesOrder.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fizz.SalesOrder.Migrations.OrderDetail
{
    [DbContext(typeof(OrderDetailContext))]
    partial class OrderDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Fizz.SalesOrder.Models.Order", b =>
                {
                    b.Property<string>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreateUserDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreateUserNo")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SignDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdaeUserDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdateUserNo")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("No");

                    b.ToTable("order");
                });

            modelBuilder.Entity("Fizz.SalesOrder.Models.OrderDetail", b =>
                {
                    b.Property<int>("ProNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreateUserDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CreateUserNo")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaterialNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SortNo")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdaeUserDate")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdateUserNo")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProNo");

                    b.HasIndex("OrderNo");

                    b.HasIndex("ProNo")
                        .IsUnique();

                    b.ToTable("detail");
                });

            modelBuilder.Entity("Fizz.SalesOrder.Models.OrderDetail", b =>
                {
                    b.HasOne("Fizz.SalesOrder.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
